name: quiz_app         # nom du package Dart
description: "A new Flutter project."
publish_to: 'none'     # privé, ne pas publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/priorite.png
    - assets/images/interdiction.jpg
    - assets/images/obligation.jpg
    - assets/images/interdiction2.png

# Configuration pour flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
